"use strict"

var seed = 1
function random() {
	var x = Math.sin(seed++) * 10000
	return x - Math.floor(x)
}

function randomFromList(list, weightFunction) {
	weightFunction = weightFunction || (() => 1)
	var weights = list.map(weightFunction)
	var sum = 0
	for (var i in weights)
		sum += weights[i]
	var randomNumber = random() * sum
	sum = 0
	for (var i in weights) {
		sum += weights[i]
		if (randomNumber < sum)
			return list[i]
	}
	return list[list.lenght - 1]
}

class Sound {
	constructor(representation, point, manner, vocalisation, syllabic) {
		this.representation = representation
		this.point = point
		this.manner = manner
		this.vocalisation = vocalisation
		this.syllabic = syllabic
	}
}

class Language {
	constructor(sounds, weights) {
		this.sounds = sounds
		this.weights = weights
	}

	randomSyllable() {
		var vocals = this.sounds.filter(e => e.syllabic)
		var consonants = this.sounds.filter(e => !e.syllabic)
		var syllable = this.weightedRandomFrom(vocals, "nucleus")
		if (random() < 0.5)
			syllable = this.weightedRandomFrom(consonants, "onset") + syllable
		if (random() < 0.5)
			syllable += this.weightedRandomFrom(consonants, "coda")
		return syllable
	}

	randomWord(max, min) {
		max = max || 4
		min = min || 2
		var word = ""
		var syllables = Math.floor(random() * (max + 1 - min)) + min
		for (var i = 0; i < syllables; i++)
			word += this.randomSyllable()
		return word
	}

	weightedRandomFrom(list, placement) {
		placement = placement || "any"
		return randomFromList(list, (e) => {
			var modifier = 1
			for (var i in this.weights)
				if (this.weightFits(this.weights[i], e, placement))
					modifier *= this.weights[i].weight
			return modifier
		}).representation
	}

	weightFits(weight, sound, placement) {
		if (weight.placement != placement && weight.placement != "any" && placement != "any")
			return false
		for (var i in weight.selection) {
			if (sound[i] != weight.selection[i])
				return false
		}
		return true
	}

	generateWords(list) {
		this.words = {}
		this.orderedWords = []
		var max = 1
		var failure = 0
		for (var i = 0; i < list.length;) {
			failure *= 0.95
			var word = this.randomWord(max, Math.max(max - 1, 1))
			if (this.words[word]) {
				failure += 0.05
				if (failure > 0.5)
					max++
				continue
			}
			this.words[word] = list[i]
			this.orderedWords.push({ word: word, ...list[i] })
			i++
		}
	}
}

var language = new Language(
	[
		new Sound("p", "labial", "stop", "voiced", false),
		new Sound("b", "labial", "stop", "unvoiced", false),
		new Sound("t", "alveolar", "stop", "voiced", false),
		new Sound("d", "alveolar", "stop", "unvoiced", false),
		new Sound("k", "velar", "stop", "voiced", false),
		new Sound("g", "velar", "stop", "unvoiced", false),
		new Sound("v", "labiodental", "fricative", "voiced", false),
		new Sound("f", "labiodental", "fricative", "unvoiced", false),
		new Sound("s", "alveolar", "fricative", "voiced", false),
		new Sound("z", "alveolar", "fricative", "unvoiced", false),
		new Sound("ð", "alveolar", "fricative", "voiced", false),
		new Sound("þ", "alveolar", "fricative", "unvoiced", false),
		new Sound("x", "velar", "fricative", "voiced", false),
		new Sound("h", "velar", "fricative", "unvoiced", false),
		new Sound("m", "labial", "nasal", "voiced", false),
		new Sound("n", "alveolar", "nasal", "voiced", false),
		new Sound("ŋ", "velar", "nasal", "voiced", false),
		new Sound("r", "velar", "trill", "voiced", false),
		new Sound("i", "alveolar", "close", "voiced", true),
		new Sound("e", "alveolar", "mid", "voiced", true),
		new Sound("a", "palatal", "open", "voiced", true),
		new Sound("o", "velar", "close", "voiced", true),
		new Sound("u", "velar", "mid", "voiced", true),
	], [
		{ placement: "any", selection: { representation: "a" }, weight: 4 },
		{ placement: "any", selection: { representation: "e" }, weight: 2 },
		{ placement: "any", selection: { representation: "i" }, weight: 2 },
		{ placement: "any", selection: { manner: "nasal" }, weight: 2 },
		{ placement: "any", selection: { point: "alveolar", manner: "stop" }, weight: 3 },
		{ placement: "any", selection: { vocalisation: "unvoiced" }, weight: 2 },
		{ placement: "coda", selection: { point: "alveolar" }, weight: 0.3 },
		{ placement: "coda", selection: { point: "velar" }, weight: 0.3 },
		{ placement: "coda", selection: { point: "velar", manner: "fricative" }, weight: 0.1 }
	]
)

var wordlist = [
	{ "meaning": "fire", "group": "The physical world" },
	{ "meaning": "rain (noun)", "group": "The physical world" },
	{ "meaning": "sun", "group": "The physical world" },
	{ "meaning": "water", "group": "The physical world" },
	{ "meaning": "star", "group": "The physical world" },
	{ "meaning": "blood", "group": "The body" },
	{ "meaning": "hair (head)", "group": "The body" },
	{ "meaning": "skin, hide", "group": "The body" },
	{ "meaning": "hand", "group": "The body" },
	{ "meaning": "head", "group": "The body" },
	{ "meaning": "ashes", "group": "The physical world" },
	{ "meaning": "sky", "group": "The physical world" },
	{ "meaning": "small, little", "group": "Spatial relations" },
	{ "meaning": "tooth", "group": "The body" },
	{ "meaning": "bone", "group": "The body" },
	{ "meaning": "man (vs. woman)", "group": "Kinship" },
	{ "meaning": "smoke (noun)", "group": "The physical world" },
	{ "meaning": "cloud", "group": "The physical world" },
	{ "meaning": "foot", "group": "The body" },
	{ "meaning": "tongue", "group": "The body" },
	{ "meaning": "nose", "group": "The body" },
	{ "meaning": "ear", "group": "The body" },
	{ "meaning": "eye", "group": "The body" },
	{ "meaning": "child", "group": "Kinship" },
	{ "meaning": "woman", "group": "Kinship" },
	{ "meaning": "wind", "group": "The physical world" },
	{ "meaning": "moon", "group": "The physical world" },
	{ "meaning": "river, stream, brook", "group": "The physical world" },
	{ "meaning": "mountain, hill", "group": "The physical world" },
	{ "meaning": "sand", "group": "The physical world" },
	{ "meaning": "walk", "group": "Motion" },
	{ "meaning": "blow", "group": "Motion" },
	{ "meaning": "sleep", "group": "The body" },
	{ "meaning": "wife", "group": "Kinship" },
	{ "meaning": "white", "group": "Sense perception" },
	{ "meaning": "wash", "group": "Basic actions and technology" },
	{ "meaning": "house", "group": "The house" },
	{ "meaning": "die, dead", "group": "The body" },
	{ "meaning": "heart", "group": "The body" },
	{ "meaning": "dog", "group": "Animals" },
	{ "meaning": "father", "group": "Kinship" },
	{ "meaning": "burn (vb trans)", "group": "The physical world" },
	{ "meaning": "woods, forest", "group": "The physical world" },
	{ "meaning": "day", "group": "Time" },
	{ "meaning": "give", "group": "Possession" },
	{ "meaning": "tie, bind", "group": "Basic actions and technology" },
	{ "meaning": "drink", "group": "Food and drink" },
	{ "meaning": "eat", "group": "Food and drink" },
	{ "meaning": "knee", "group": "The body" },
	{ "meaning": "arm", "group": "The body" },
	{ "meaning": "fish", "group": "Animals" },
	{ "meaning": "night", "group": "Time" },
	{ "meaning": "black", "group": "Sense perception" },
	{ "meaning": "red", "group": "Sense perception" },
	{ "meaning": "dry", "group": "Sense perception" },
	{ "meaning": "large, big", "group": "Spatial relations" },
	{ "meaning": "kill", "group": "The body" },
	{ "meaning": "bite", "group": "The body" },
	{ "meaning": "shoulder", "group": "The body" },
	{ "meaning": "neck", "group": "The body" },
	{ "meaning": "mouth", "group": "The body" },
	{ "meaning": "face", "group": "The body" },
	{ "meaning": "tail", "group": "The body" },
	{ "meaning": "I", "group": "Kinship" },
	{ "meaning": "dust", "group": "The physical world" },
	{ "meaning": "see", "group": "Sense perception" },
	{ "meaning": "cold", "group": "Sense perception" },
	{ "meaning": "stand", "group": "Spatial relations" },
	{ "meaning": "come", "group": "Motion" },
	{ "meaning": "fall", "group": "Motion" },
	{ "meaning": "root", "group": "Agriculture and vegetation" },
	{ "meaning": "stomach", "group": "The body" },
	{ "meaning": "grandfather", "group": "Kinship" },
	{ "meaning": "husband", "group": "Kinship" },
	{ "meaning": "earth, land", "group": "The physical world" },
	{ "meaning": "hear", "group": "Sense perception" },
	{ "meaning": "heavy", "group": "Sense perception" },
	{ "meaning": "much, many", "group": "Quantity" },
	{ "meaning": "sit", "group": "Spatial relations" },
	{ "meaning": "strike (hit, beat)", "group": "Basic actions and technology" },
	{ "meaning": "back", "group": "The body" },
	{ "meaning": "bird", "group": "Animals" },
	{ "meaning": "you (singular)", "group": "Kinship" },
	{ "meaning": "person, human being", "group": "Kinship" },
	{ "meaning": "stone, rock", "group": "The physical world" },
	{ "meaning": "hot", "group": "Sense perception" },
	{ "meaning": "fear, fright", "group": "Emotions and values" },
	{ "meaning": "bad", "group": "Emotions and values" },
	{ "meaning": "speak, talk", "group": "Speech and language" },
	{ "meaning": "fly (vb)", "group": "Motion" },
	{ "meaning": "cut", "group": "Basic actions and technology" },
	{ "meaning": "leaf", "group": "Agriculture and vegetation" },
	{ "meaning": "grass", "group": "Agriculture and vegetation" },
	{ "meaning": "hunger", "group": "Food and drink" },
	{ "meaning": "live, living, life", "group": "The body" },
	{ "meaning": "spit", "group": "The body" },
	{ "meaning": "chest", "group": "The body" },
	{ "meaning": "leg", "group": "The body" },
	{ "meaning": "fingernail", "group": "The body" },
	{ "meaning": "forehead", "group": "The body" },
	{ "meaning": "beard", "group": "The body" },
	{ "meaning": "sweet", "group": "Sense perception" },
	{ "meaning": "wet, damp", "group": "Sense perception" },
	{ "meaning": "joyful, glad, happy", "group": "Emotions and values" },
	{ "meaning": "laugh", "group": "Emotions and values" },
	{ "meaning": "good", "group": "Emotions and values" },
	{ "meaning": "name", "group": "Speech and language" },
	{ "meaning": "old", "group": "Time" },
	{ "meaning": "full", "group": "Quantity" },
	{ "meaning": "long", "group": "Spatial relations" },
	{ "meaning": "go", "group": "Motion" },
	{ "meaning": "rope, cord", "group": "Basic actions and technology" },
	{ "meaning": "do, make", "group": "Basic actions and technology" },
	{ "meaning": "meat", "group": "Food and drink" },
	{ "meaning": "liver", "group": "The body" },
	{ "meaning": "horn", "group": "The body" },
	{ "meaning": "light, kindle, ignite", "group": "The physical world" },
	{ "meaning": "shade, shadow", "group": "The physical world" },
	{ "meaning": "darkness", "group": "The physical world" },
	{ "meaning": "sing", "group": "Speech and language" },
	{ "meaning": "every, all", "group": "Quantity" },
	{ "meaning": "near (adv)", "group": "Spatial relations" },
	{ "meaning": "left (side)", "group": "Spatial relations" },
	{ "meaning": "break", "group": "Basic actions and technology" },
	{ "meaning": "clothing, clothes", "group": "Clothing and grooming" },
	{ "meaning": "salt", "group": "Food and drink" },
	{ "meaning": "strong, mighty, powerful", "group": "The body" },
	{ "meaning": "breast (of woman)", "group": "The body" },
	{ "meaning": "feather", "group": "The body" },
	{ "meaning": "wing", "group": "The body" },
	{ "meaning": "finger", "group": "The body" },
	{ "meaning": "rib", "group": "The body" },
	{ "meaning": "snake", "group": "Animals" },
	{ "meaning": "son", "group": "Kinship" },
	{ "meaning": "light (noun)", "group": "The physical world" },
	{ "meaning": "thunder", "group": "The physical world" },
	{ "meaning": "know", "group": "Cognition" },
	{ "meaning": "ax", "group": "Basic actions and technology" },
	{ "meaning": "dig", "group": "Agriculture and vegetation" },
	{ "meaning": "medicine, drug", "group": "The body" },
	{ "meaning": "sick, sickness", "group": "The body" },
	{ "meaning": "bury (the dead)", "group": "The body" },
	{ "meaning": "lip", "group": "The body" },
	{ "meaning": "mouse, rat", "group": "Animals" },
	{ "meaning": "grandmother", "group": "Kinship" },
	{ "meaning": "firewood", "group": "The physical world" },
	{ "meaning": "wood", "group": "The physical world" },
	{ "meaning": "mud", "group": "The physical world" },
	{ "meaning": "look, look at", "group": "Sense perception" },
	{ "meaning": "sharp", "group": "Sense perception" },
	{ "meaning": "no, negative", "group": "Cognition" },
	{ "meaning": "swift, fast, quick", "group": "Time" },
	{ "meaning": "new", "group": "Time" },
	{ "meaning": "little (quantity), few", "group": "Quantity" },
	{ "meaning": "road", "group": "Motion" },
	{ "meaning": "reach, arrive", "group": "Motion" },
	{ "meaning": "run", "group": "Motion" },
	{ "meaning": "flower", "group": "Agriculture and vegetation" },
	{ "meaning": "tired, weary", "group": "The body" },
	{ "meaning": "wake up", "group": "The body" },
	{ "meaning": "breathe, breath", "group": "The body" },
	{ "meaning": "throat", "group": "The body" },
	{ "meaning": "flesh", "group": "The body" },
	{ "meaning": "he/she/it", "group": "Kinship" },
	{ "meaning": "yellow", "group": "Sense perception" },
	{ "meaning": "love", "group": "Emotions and values" },
	{ "meaning": "cry, weep", "group": "Emotions and values" },
	{ "meaning": "friend, companion", "group": "Social and political relations" },
	{ "meaning": "hole", "group": "Spatial relations" },
	{ "meaning": "right (side)", "group": "Spatial relations" },
	{ "meaning": "seek, look for", "group": "Possession" },
	{ "meaning": "carry (bear)", "group": "Motion" },
	{ "meaning": "swim", "group": "Motion" },
	{ "meaning": "throw", "group": "Motion" },
	{ "meaning": "pull", "group": "Basic actions and technology" },
	{ "meaning": "door, gate", "group": "The house" },
	{ "meaning": "blind", "group": "The body" },
	{ "meaning": "eyebrow", "group": "The body" },
	{ "meaning": "fly", "group": "Animals" },
	{ "meaning": "daughter", "group": "Kinship" },
	{ "meaning": "boy", "group": "Kinship" },
	{ "meaning": "male", "group": "Kinship" },
	{ "meaning": "spring, well", "group": "The physical world" },
	{ "meaning": "straight", "group": "Spatial relations" },
	{ "meaning": "wide, broad", "group": "Spatial relations" },
	{ "meaning": "hide, conceal", "group": "Spatial relations" },
	{ "meaning": "lie down", "group": "Spatial relations" },
	{ "meaning": "jump, leap", "group": "Motion" },
	{ "meaning": "tree", "group": "Agriculture and vegetation" },
	{ "meaning": "branch", "group": "Agriculture and vegetation" },
	{ "meaning": "thread", "group": "Clothing and grooming" },
	{ "meaning": "egg", "group": "Food and drink" },
	{ "meaning": "food", "group": "Food and drink" },
	{ "meaning": "vomit", "group": "The body" },
	{ "meaning": "intestines, guts", "group": "The body" },
	{ "meaning": "body", "group": "The body" },
	{ "meaning": "lightning", "group": "The physical world" },
	{ "meaning": "anger", "group": "Emotions and values" },
	{ "meaning": "beautiful", "group": "Emotions and values" },
	{ "meaning": "alone, only", "group": "Quantity" },
	{ "meaning": "thin (in dimension)", "group": "Spatial relations" },
	{ "meaning": "short", "group": "Spatial relations" },
	{ "meaning": "grow", "group": "Spatial relations" },
	{ "meaning": "middle, center", "group": "Spatial relations" },
	{ "meaning": "open", "group": "Spatial relations" },
	{ "meaning": "take", "group": "Possession" },
	{ "meaning": "rub, wipe", "group": "Basic actions and technology" },
	{ "meaning": "seed", "group": "Agriculture and vegetation" },
	{ "meaning": "bed", "group": "The house" },
	{ "meaning": "sew", "group": "Clothing and grooming" },
	{ "meaning": "pot, cooking vessel", "group": "Food and drink" },
	{ "meaning": "roast, fry", "group": "Food and drink" },
	{ "meaning": "cook", "group": "Food and drink" },
	{ "meaning": "pregnant", "group": "The body" },
	{ "meaning": "cough", "group": "The body" },
	{ "meaning": "worm", "group": "Animals" },
	{ "meaning": "cat", "group": "Animals" },
	{ "meaning": "you (plural)", "group": "Kinship" },
	{ "meaning": "fog", "group": "The physical world" },
	{ "meaning": "year", "group": "Time" },
	{ "meaning": "lie, tell lies", "group": "Emotions and values" },
	{ "meaning": "think (= reflect)", "group": "Cognition" },
	{ "meaning": "shout, cry out", "group": "Speech and language" },
	{ "meaning": "say", "group": "Speech and language" },
	{ "meaning": "ask (question, inquire)", "group": "Speech and language" },
	{ "meaning": "finish", "group": "Time" },
	{ "meaning": "path", "group": "Motion" },
	{ "meaning": "bring", "group": "Motion" },
	{ "meaning": "dance", "group": "Motion" },
	{ "meaning": "work", "group": "Basic actions and technology" },
	{ "meaning": "grease, fat", "group": "Food and drink" },
	{ "meaning": "suck", "group": "Food and drink" },
	{ "meaning": "cure, heal", "group": "The body" },
	{ "meaning": "bathe", "group": "The body" },
	{ "meaning": "defecate", "group": "The body" },
	{ "meaning": "dream", "group": "The body" },
	{ "meaning": "grandson", "group": "Kinship" },
	{ "meaning": "bitter", "group": "Sense perception" },
	{ "meaning": "blue", "group": "Sense perception" },
	{ "meaning": "dirty, soiled", "group": "Sense perception" },
	{ "meaning": "pain", "group": "Emotions and values" },
	{ "meaning": "forget", "group": "Cognition" },
	{ "meaning": "where?", "group": "Cognition" },
	{ "meaning": "now", "group": "Time" },
	{ "meaning": "thick (in dimension)", "group": "Spatial relations" },
	{ "meaning": "push, shove", "group": "Motion" },
	{ "meaning": "wind, wrap", "group": "Motion" },
	{ "meaning": "sweep", "group": "Basic actions and technology" },
	{ "meaning": "needle", "group": "Clothing and grooming" },
	{ "meaning": "boil (vb)", "group": "Food and drink" },
	{ "meaning": "deaf", "group": "The body" },
	{ "meaning": "urinate", "group": "The body" },
	{ "meaning": "navel", "group": "The body" },
	{ "meaning": "girl", "group": "Kinship" },
	{ "meaning": "plain, field", "group": "The physical world" },
	{ "meaning": "play", "group": "Emotions and values" },
	{ "meaning": "fight (vb)", "group": "Warfare and hunting" },
	{ "meaning": "arrow", "group": "Warfare and hunting" },
	{ "meaning": "round", "group": "Spatial relations" },
	{ "meaning": "narrow", "group": "Spatial relations" },
	{ "meaning": "seize, grasp", "group": "Possession" },
	{ "meaning": "enter", "group": "Motion" },
	{ "meaning": "raise, lift", "group": "Motion" },
	{ "meaning": "tear", "group": "Basic actions and technology" },
	{ "meaning": "bark", "group": "Agriculture and vegetation" },
	{ "meaning": "weak", "group": "The body" },
	{ "meaning": "cheek", "group": "The body" },
	{ "meaning": "brain", "group": "The body" },
	{ "meaning": "bee", "group": "Animals" },
	{ "meaning": "spider", "group": "Animals" },
	{ "meaning": "louse", "group": "Animals" },
	{ "meaning": "infant, baby", "group": "Kinship" },
	{ "meaning": "earth=ground, soil", "group": "The physical world" },
	{ "meaning": "tomorrow", "group": "Time" },
	{ "meaning": "hard", "group": "Sense perception" },
	{ "meaning": "tear (noun)", "group": "Emotions and values" },
	{ "meaning": "write", "group": "Speech and language" },
	{ "meaning": "first", "group": "Quantity" },
	{ "meaning": "deep", "group": "Spatial relations" },
	{ "meaning": "cover", "group": "Spatial relations" },
	{ "meaning": "rise", "group": "Motion" },
	{ "meaning": "intoxicated", "group": "The body" },
	{ "meaning": "lazy", "group": "The body" },
	{ "meaning": "thigh", "group": "The body" },
	{ "meaning": "shore", "group": "The physical world" },
	{ "meaning": "when?", "group": "Cognition" },
	{ "meaning": "call (=summon)", "group": "Speech and language" },
	{ "meaning": "steal", "group": "Law" },
	{ "meaning": "side", "group": "Spatial relations" },
	{ "meaning": "high", "group": "Spatial relations" },
	{ "meaning": "buy", "group": "Possession" },
	{ "meaning": "find", "group": "Possession" },
	{ "meaning": "turn over", "group": "Motion" },
	{ "meaning": "comb", "group": "Clothing and grooming" },
	{ "meaning": "hat, cap", "group": "Clothing and grooming" },
	{ "meaning": "swallow", "group": "Food and drink" },
	{ "meaning": "chew", "group": "Food and drink" },
	{ "meaning": "frog", "group": "Animals" },
	{ "meaning": "pig", "group": "Animals" },
	{ "meaning": "old man", "group": "Kinship" },
	{ "meaning": "marry", "group": "Kinship" },
	{ "meaning": "rainbow", "group": "The physical world" },
	{ "meaning": "tree (cf 08.600)", "group": "The physical world" },
	{ "meaning": "month", "group": "Time" },
	{ "meaning": "green", "group": "Sense perception" },
	{ "meaning": "soft", "group": "Sense perception" },
	{ "meaning": "teach", "group": "Cognition" },
	{ "meaning": "what?", "group": "Cognition" },
	{ "meaning": "shut, close", "group": "Spatial relations" },
	{ "meaning": "put", "group": "Spatial relations" },
	{ "meaning": "flee", "group": "Motion" },
	{ "meaning": "hang up", "group": "Basic actions and technology" },
	{ "meaning": "bend", "group": "Basic actions and technology" },
	{ "meaning": "milk (noun)", "group": "Food and drink" },
	{ "meaning": "crush, grind", "group": "Food and drink" },
	{ "meaning": "thirst", "group": "Food and drink" },
	{ "meaning": "rotten", "group": "Food and drink" },
	{ "meaning": "born (to be)", "group": "The body" },
	{ "meaning": "buttocks", "group": "The body" },
	{ "meaning": "elbow", "group": "The body" },
	{ "meaning": "they", "group": "Kinship" },
	{ "meaning": "true", "group": "Emotions and values" },
	{ "meaning": "who?", "group": "Cognition" },
	{ "meaning": "remain, stay", "group": "Spatial relations" },
	{ "meaning": "go down", "group": "Motion" },
	{ "meaning": "shake", "group": "Motion" },
	{ "meaning": "basket", "group": "Basic actions and technology" },
	{ "meaning": "squeeze, wring", "group": "Basic actions and technology" },
	{ "meaning": "put on (clothes)", "group": "Clothing and grooming" },
	{ "meaning": "knife (2)", "group": "Food and drink" },
	{ "meaning": "lick", "group": "The body" },
	{ "meaning": "nest", "group": "Animals" },
	{ "meaning": "duck", "group": "Animals" },
	{ "meaning": "today", "group": "Time" },
	{ "meaning": "listen", "group": "Sense perception" },
	{ "meaning": "learn", "group": "Cognition" },
	{ "meaning": "remember", "group": "Cognition" },
	{ "meaning": "yes, affirmative", "group": "Cognition" },
	{ "meaning": "edge", "group": "Spatial relations" },
	{ "meaning": "come back", "group": "Motion" },
	{ "meaning": "stir, mix", "group": "Food and drink" },
	{ "meaning": "wound, sore", "group": "The body" },
	{ "meaning": "lung", "group": "The body" },
	{ "meaning": "young man (adolescent)", "group": "Kinship" },
	{ "meaning": "female", "group": "Kinship" },
	{ "meaning": "again", "group": "Time" },
	{ "meaning": "morning", "group": "Time" },
	{ "meaning": "yesterday", "group": "Time" },
	{ "meaning": "soul, spirit", "group": "Emotions and values" },
	{ "meaning": "village", "group": "Social and political relations" },
	{ "meaning": "help, aid", "group": "Social and political relations" },
	{ "meaning": "like, similar", "group": "Spatial relations" },
	{ "meaning": "top", "group": "Spatial relations" },
	{ "meaning": "split", "group": "Basic actions and technology" },
	{ "meaning": "ripe", "group": "Food and drink" },
	{ "meaning": "rest", "group": "The body" },
	{ "meaning": "perspire", "group": "The body" },
	{ "meaning": "testicle", "group": "The body" },
	{ "meaning": "jaw", "group": "The body" },
	{ "meaning": "horse (equine)", "group": "Animals" },
	{ "meaning": "relatives, kinsmen", "group": "Kinship" },
	{ "meaning": "dawn", "group": "Time" },
	{ "meaning": "how?", "group": "Cognition" },
	{ "meaning": "ask, request", "group": "Speech and language" },
	{ "meaning": "slow", "group": "Time" },
	{ "meaning": "money", "group": "Possession" },
	{ "meaning": "follow", "group": "Motion" },
	{ "meaning": "go away, depart", "group": "Motion" },
	{ "meaning": "clay", "group": "Basic actions and technology" },
	{ "meaning": "roof", "group": "The house" },
	{ "meaning": "dwell, live", "group": "The house" },
	{ "meaning": "honey", "group": "Food and drink" },
	{ "meaning": "naked, bare", "group": "The body" },
	{ "meaning": "lame", "group": "The body" },
	{ "meaning": "swelling", "group": "The body" },
	{ "meaning": "penis", "group": "The body" },
	{ "meaning": "ant", "group": "Animals" },
	{ "meaning": "deer", "group": "Animals" },
	{ "meaning": "bat", "group": "Animals" },
	{ "meaning": "widow", "group": "Kinship" },
	{ "meaning": "charcoal", "group": "The physical world" },
	{ "meaning": "extinguish", "group": "The physical world" },
	{ "meaning": "stinking, bad smelling", "group": "Sense perception" },
	{ "meaning": "acid, sour", "group": "Sense perception" },
	{ "meaning": "show", "group": "Sense perception" },
	{ "meaning": "grief, sorrow, sadness", "group": "Emotions and values" },
	{ "meaning": "voice", "group": "Speech and language" },
	{ "meaning": "language", "group": "Speech and language" },
	{ "meaning": "bow", "group": "Warfare and hunting" },
	{ "meaning": "hunt", "group": "Warfare and hunting" },
	{ "meaning": "thief", "group": "Law" },
	{ "meaning": "send", "group": "Motion" },
	{ "meaning": "flow", "group": "Motion" },
	{ "meaning": "pour", "group": "Basic actions and technology" },
	{ "meaning": "fruit", "group": "Food and drink" },
	{ "meaning": "raw", "group": "Food and drink" },
	{ "meaning": "toe", "group": "The body" },
	{ "meaning": "cow", "group": "Animals" },
	{ "meaning": "old woman", "group": "Kinship" },
	{ "meaning": "believe", "group": "Cognition" },
	{ "meaning": "word", "group": "Speech and language" },
	{ "meaning": "join, unite", "group": "Spatial relations" },
	{ "meaning": "collect, gather", "group": "Spatial relations" },
	{ "meaning": "sell", "group": "Possession" },
	{ "meaning": "poor", "group": "Possession" },
	{ "meaning": "lose", "group": "Possession" },
	{ "meaning": "belt, girdle", "group": "Clothing and grooming" },
	{ "meaning": "spoon", "group": "Food and drink" },
	{ "meaning": "sneeze", "group": "The body" },
	{ "meaning": "butterfly", "group": "Animals" },
	{ "meaning": "mosquito", "group": "Animals" },
	{ "meaning": "hen", "group": "Animals" },
	{ "meaning": "animal", "group": "Animals" },
	{ "meaning": "father-in-law (of a man)", "group": "Kinship" },
	{ "meaning": "shine", "group": "Sense perception" },
	{ "meaning": "light (in weight)", "group": "Sense perception" },
	{ "meaning": "shame (noun)", "group": "Emotions and values" },
	{ "meaning": "foolish, stupid", "group": "Cognition" },
	{ "meaning": "people (populace)", "group": "Social and political relations" },
	{ "meaning": "meet", "group": "Social and political relations" },
	{ "meaning": "begin, beginning", "group": "Time" },
	{ "meaning": "empty", "group": "Quantity" },
	{ "meaning": "separate", "group": "Spatial relations" },
	{ "meaning": "pay (vb)", "group": "Possession" },
	{ "meaning": "creep, crawl", "group": "Motion" },
	{ "meaning": "move", "group": "Motion" },
	{ "meaning": "fold", "group": "Basic actions and technology" },
	{ "meaning": "peel", "group": "Food and drink" },
	{ "meaning": "armpit", "group": "The body" },
	{ "meaning": "eyelash", "group": "The body" },
	{ "meaning": "son-in-law (of a man)", "group": "Kinship" },
	{ "meaning": "granddaughter", "group": "Kinship" },
	{ "meaning": "burn (vb intrans)", "group": "The physical world" },
	{ "meaning": "foam", "group": "The physical world" },
	{ "meaning": "evening", "group": "Time" },
	{ "meaning": "quiet, silence", "group": "Sense perception" },
	{ "meaning": "warm", "group": "Sense perception" },
	{ "meaning": "enough", "group": "Quantity" },
	{ "meaning": "chair", "group": "The house" },
	{ "meaning": "scrape", "group": "Food and drink" },
	{ "meaning": "grave, tomb", "group": "The body" },
	{ "meaning": "palm of hand", "group": "The body" },
	{ "meaning": "mother-in-law (of a man)", "group": "Kinship" },
	{ "meaning": "cave", "group": "The physical world" },
	{ "meaning": "smooth", "group": "Sense perception" },
	{ "meaning": "kiss", "group": "Emotions and values" },
	{ "meaning": "desire, want", "group": "Emotions and values" },
	{ "meaning": "half", "group": "Quantity" },
	{ "meaning": "tall", "group": "Spatial relations" },
	{ "meaning": "twist", "group": "Motion" },
	{ "meaning": "field (for cultivation)", "group": "Agriculture and vegetation" },
	{ "meaning": "lamp, torch", "group": "The house" },
	{ "meaning": "wall", "group": "The house" },
	{ "meaning": "weave", "group": "Clothing and grooming" },
	{ "meaning": "cloth", "group": "Clothing and grooming" },
	{ "meaning": "yawn, gape", "group": "The body" },
	{ "meaning": "dove", "group": "Animals" },
	{ "meaning": "owl", "group": "Animals" },
	{ "meaning": "cock, rooster", "group": "Animals" },
	{ "meaning": "lake", "group": "The physical world" },
	{ "meaning": "sound, noise", "group": "Sense perception" },
	{ "meaning": "touch", "group": "Sense perception" },
	{ "meaning": "ugly", "group": "Emotions and values" },
	{ "meaning": "last", "group": "Quantity" },
	{ "meaning": "crooked", "group": "Spatial relations" },
	{ "meaning": "pointed", "group": "Spatial relations" },
	{ "meaning": "place", "group": "Spatial relations" },
	{ "meaning": "go out", "group": "Motion" },
	{ "meaning": "climb", "group": "Motion" },
	{ "meaning": "slide, slip", "group": "Motion" },
	{ "meaning": "turn around", "group": "Motion" },
	{ "meaning": "knife", "group": "Basic actions and technology" },
	{ "meaning": "plant (vb)", "group": "Agriculture and vegetation" },
	{ "meaning": "bald", "group": "The body" },
	{ "meaning": "well, health", "group": "The body" },
	{ "meaning": "heel", "group": "The body" },
	{ "meaning": "mucus (nasal)", "group": "The body" },
	{ "meaning": "chicken", "group": "Animals" },
	{ "meaning": "dew", "group": "The physical world" },
	{ "meaning": "understand", "group": "Cognition" },
	{ "meaning": "shoot", "group": "Warfare and hunting" },
	{ "meaning": "young", "group": "Time" },
	{ "meaning": "hold", "group": "Possession" },
	{ "meaning": "sink", "group": "Motion" },
	{ "meaning": "soup, broth", "group": "Food and drink" },
	{ "meaning": "itch", "group": "The body" },
	{ "meaning": "shiver", "group": "The body" },
	{ "meaning": "chin", "group": "The body" },
	{ "meaning": "body hair", "group": "The body" },
	{ "meaning": "mother", "group": "Kinship" },
	{ "meaning": "young woman (adolescent)", "group": "Kinship" },
	{ "meaning": "smell (vb intrans)", "group": "Sense perception" },
	{ "meaning": "salty", "group": "Sense perception" },
	{ "meaning": "bright", "group": "Sense perception" },
	{ "meaning": "why?", "group": "Cognition" },
	{ "meaning": "silent (be)", "group": "Speech and language" },
	{ "meaning": "answer", "group": "Speech and language" },
	{ "meaning": "always", "group": "Time" },
	{ "meaning": "count", "group": "Quantity" },
	{ "meaning": "change", "group": "Spatial relations" },
	{ "meaning": "get, obtain", "group": "Possession" },
	{ "meaning": "go up", "group": "Motion" },
	{ "meaning": "press", "group": "Basic actions and technology" },
	{ "meaning": "spread out", "group": "Basic actions and technology" },
	{ "meaning": "blanket", "group": "The house" },
	{ "meaning": "mirror", "group": "Clothing and grooming" },
	{ "meaning": "fever", "group": "The body" },
	{ "meaning": "fragrant, good smelling", "group": "Sense perception" },
	{ "meaning": "hate", "group": "Emotions and values" },
	{ "meaning": "which?", "group": "Cognition" },
	{ "meaning": "cease, stop", "group": "Time" },
	{ "meaning": "hasten, hurry", "group": "Time" },
	{ "meaning": "end", "group": "Spatial relations" },
	{ "meaning": "dear (costly, expensive)", "group": "Possession" },
	{ "meaning": "rich", "group": "Possession" },
	{ "meaning": "thing", "group": "Possession" },
	{ "meaning": "have", "group": "Possession" },
	{ "meaning": "stretch", "group": "Basic actions and technology" },
	{ "meaning": "chop, hew", "group": "Basic actions and technology" },
	{ "meaning": "post, pole", "group": "The house" },
	{ "meaning": "shoe", "group": "Clothing and grooming" },
	{ "meaning": "corpse", "group": "The body" },
	{ "meaning": "have sexual intercourse", "group": "The body" },
	{ "meaning": "spine", "group": "The body" },
	{ "meaning": "wasp", "group": "Animals" },
	{ "meaning": "orphan", "group": "Kinship" },
	{ "meaning": "right, correct", "group": "Emotions and values" },
	{ "meaning": "insane, crazy", "group": "Cognition" },
	{ "meaning": "whistle", "group": "Speech and language" },
	{ "meaning": "flat", "group": "Spatial relations" },
	{ "meaning": "avaricious, stingy", "group": "Possession" },
	{ "meaning": "float", "group": "Motion" },
	{ "meaning": "weave, plait", "group": "Basic actions and technology" },
	{ "meaning": "build", "group": "Basic actions and technology" },
	{ "meaning": "broom", "group": "Basic actions and technology" },
	{ "meaning": "fence", "group": "Agriculture and vegetation" },
	{ "meaning": "trousers", "group": "Clothing and grooming" },
	{ "meaning": "leather", "group": "Clothing and grooming" },
	{ "meaning": "meal, flour", "group": "Food and drink" },
	{ "meaning": "mute", "group": "The body" },
	{ "meaning": "physician", "group": "The body" },
	{ "meaning": "ankle", "group": "The body" },
	{ "meaning": "thumb", "group": "The body" },
	{ "meaning": "beak", "group": "The body" },
	{ "meaning": "nephew", "group": "Kinship" },
	{ "meaning": "older brother", "group": "Kinship" },
	{ "meaning": "flame (noun)", "group": "The physical world" },
	{ "meaning": "paper", "group": "Speech and language" },
	{ "meaning": "more", "group": "Quantity" },
	{ "meaning": "corner", "group": "Spatial relations" },
	{ "meaning": "stab", "group": "Basic actions and technology" },
	{ "meaning": "untie", "group": "Basic actions and technology" },
	{ "meaning": "green, unripe", "group": "Food and drink" },
	{ "meaning": "pus", "group": "The body" },
	{ "meaning": "vein, artery", "group": "The body" },
	{ "meaning": "lizard", "group": "Animals" },
	{ "meaning": "younger brother", "group": "Kinship" },
	{ "meaning": "clean", "group": "Sense perception" },
	{ "meaning": "chief, chieftain", "group": "Social and political relations" },
	{ "meaning": "east", "group": "Spatial relations" },
	{ "meaning": "bottom", "group": "Spatial relations" },
	{ "meaning": "drip", "group": "Motion" },
	{ "meaning": "roll", "group": "Motion" },
	{ "meaning": "bore", "group": "Basic actions and technology" },
	{ "meaning": "cut down", "group": "Basic actions and technology" },
	{ "meaning": "floor", "group": "The house" },
	{ "meaning": "cup, drinking vessel", "group": "Food and drink" },
	{ "meaning": "poison", "group": "The body" },
	{ "meaning": "boil (noun)", "group": "The body" },
	{ "meaning": "skull", "group": "The body" },
	{ "meaning": "daughter-in-law (of a man)", "group": "Kinship" },
	{ "meaning": "read", "group": "Speech and language" },
	{ "meaning": "immediately", "group": "Time" },
	{ "meaning": "pursue", "group": "Motion" },
	{ "meaning": "catch (ball)", "group": "Motion" },
	{ "meaning": "tobacco", "group": "Agriculture and vegetation" },
	{ "meaning": "cooked", "group": "Food and drink" },
	{ "meaning": "hip", "group": "The body" },
	{ "meaning": "kidney", "group": "The body" },
	{ "meaning": "claw", "group": "The body" },
	{ "meaning": "parrot", "group": "Animals" },
	{ "meaning": "world", "group": "The physical world" },
	{ "meaning": "difficult", "group": "Cognition" },
	{ "meaning": "part, piece", "group": "Quantity" },
	{ "meaning": "ten", "group": "Quantity" },
	{ "meaning": "west", "group": "Spatial relations" },
	{ "meaning": "divide", "group": "Spatial relations" },
	{ "meaning": "share (distribute)", "group": "Possession" },
	{ "meaning": "harm, injure, damage", "group": "Possession" },
	{ "meaning": "kneel", "group": "Motion" },
	{ "meaning": "flay, skin", "group": "Basic actions and technology" },
	{ "meaning": "knot (noun)", "group": "Basic actions and technology" },
	{ "meaning": "maize, corn", "group": "Agriculture and vegetation" },
	{ "meaning": "plate", "group": "Food and drink" },
	{ "meaning": "nipple, teat", "group": "The body" },
	{ "meaning": "footprint", "group": "The body" },
	{ "meaning": "wrist", "group": "The body" },
	{ "meaning": "snail", "group": "Animals" },
	{ "meaning": "monkey", "group": "Animals" },
	{ "meaning": "afternoon", "group": "Time" },
	{ "meaning": "winter", "group": "Time" },
	{ "meaning": "how many?", "group": "Cognition" },
	{ "meaning": "how much?", "group": "Cognition" },
	{ "meaning": "tell story", "group": "Speech and language" },
	{ "meaning": "preserve, look after", "group": "Possession" },
	{ "meaning": "kick", "group": "Motion" },
	{ "meaning": "nail", "group": "Basic actions and technology" },
	{ "meaning": "cotton", "group": "Clothing and grooming" },
	{ "meaning": "sieve, strain", "group": "Food and drink" },
	{ "meaning": "snore", "group": "The body" },
	{ "meaning": "nostril", "group": "The body" },
	{ "meaning": "eyelid", "group": "The body" },
	{ "meaning": "turtle", "group": "Animals" },
	{ "meaning": "flea", "group": "Animals" },
	{ "meaning": "hawk", "group": "Animals" },
	{ "meaning": "embers", "group": "The physical world" },
	{ "meaning": "envy, jealousy", "group": "Emotions and values" },
	{ "meaning": "enemy", "group": "Social and political relations" },
	{ "meaning": "strife, quarrel", "group": "Social and political relations" },
	{ "meaning": "demon (evil spirit)", "group": "Religion and belief" },
	{ "meaning": "low", "group": "Spatial relations" },
	{ "meaning": "pile up", "group": "Spatial relations" },
	{ "meaning": "approach", "group": "Motion" },
	{ "meaning": "waist", "group": "The body" },
	{ "meaning": "nape of neck", "group": "The body" },
	{ "meaning": "family", "group": "Kinship" },
	{ "meaning": "ancestors", "group": "Kinship" },
	{ "meaning": "niece", "group": "Kinship" },
	{ "meaning": "storm", "group": "The physical world" },
	{ "meaning": "sea", "group": "The physical world" },
	{ "meaning": "smell (vb trans)", "group": "Sense perception" },
	{ "meaning": "rough", "group": "Sense perception" },
	{ "meaning": "embrace", "group": "Emotions and values" },
	{ "meaning": "choose", "group": "Emotions and values" },
	{ "meaning": "book", "group": "Speech and language" },
	{ "meaning": "one", "group": "Quantity" },
	{ "meaning": "bridge", "group": "Motion" },
	{ "meaning": "smoke (tobacco)", "group": "Agriculture and vegetation" },
	{ "meaning": "sow", "group": "Agriculture and vegetation" },
	{ "meaning": "braid", "group": "Clothing and grooming" },
	{ "meaning": "necklace", "group": "Clothing and grooming" },
	{ "meaning": "summer", "group": "Time" },
	{ "meaning": "obey", "group": "Social and political relations" },
	{ "meaning": "fishhook", "group": "Warfare and hunting" },
	{ "meaning": "measure", "group": "Spatial relations" },
	{ "meaning": "scissors, shears", "group": "Basic actions and technology" },
	{ "meaning": "tree trunk", "group": "Agriculture and vegetation" },
	{ "meaning": "table", "group": "The house" },
	{ "meaning": "earring", "group": "Clothing and grooming" },
	{ "meaning": "spin", "group": "Clothing and grooming" },
	{ "meaning": "calf of leg", "group": "The body" },
	{ "meaning": "fishscale", "group": "Animals" },
	{ "meaning": "female (adj)", "group": "Animals" },
	{ "meaning": "younger sister", "group": "Kinship" },
	{ "meaning": "older sister", "group": "Kinship" },
	{ "meaning": "sister", "group": "Kinship" },
	{ "meaning": "brother", "group": "Kinship" },
	{ "meaning": "lightning (as striking)", "group": "The physical world" },
	{ "meaning": "cliff, precipice", "group": "The physical world" },
	{ "meaning": "anxiety, worry", "group": "Emotions and values" },
	{ "meaning": "brave", "group": "Emotions and values" },
	{ "meaning": "try, attempt", "group": "Cognition" },
	{ "meaning": "country", "group": "Social and political relations" },
	{ "meaning": "city, town", "group": "Social and political relations" },
	{ "meaning": "stranger", "group": "Social and political relations" },
	{ "meaning": "two", "group": "Quantity" },
	{ "meaning": "remains, left overs", "group": "Spatial relations" },
	{ "meaning": "board", "group": "The house" },
	{ "meaning": "hut", "group": "The house" },
	{ "meaning": "oil", "group": "Food and drink" },
	{ "meaning": "drowned", "group": "The body" },
	{ "meaning": "blink", "group": "The body" },
	{ "meaning": "rabbit", "group": "Animals" },
	{ "meaning": "pinch", "group": "Sense perception" },
	{ "meaning": "teacher", "group": "Cognition" },
	{ "meaning": "late", "group": "Time" },
	{ "meaning": "some", "group": "Quantity" },
	{ "meaning": "shallow", "group": "Spatial relations" },
	{ "meaning": "mushroom", "group": "Agriculture and vegetation" },
	{ "meaning": "ditch", "group": "Agriculture and vegetation" },
	{ "meaning": "ladder", "group": "The house" },
	{ "meaning": "bean", "group": "Food and drink" },
	{ "meaning": "bowl", "group": "Food and drink" },
	{ "meaning": "male (adj)", "group": "Animals" },
	{ "meaning": "we", "group": "Kinship" },
	{ "meaning": "multitude, crowd", "group": "Quantity" },
	{ "meaning": "cheap", "group": "Possession" },
	{ "meaning": "lead (vb)", "group": "Motion" },
	{ "meaning": "disappear", "group": "Motion" },
	{ "meaning": "gold", "group": "Basic actions and technology" },
	{ "meaning": "cultivate, till", "group": "Agriculture and vegetation" },
	{ "meaning": "choke", "group": "Food and drink" },
	{ "meaning": "cold (catarrh)", "group": "The body" },
	{ "meaning": "match (noun)", "group": "The physical world" },
	{ "meaning": "swamp", "group": "The physical world" },
	{ "meaning": "blunt, dull", "group": "Sense perception" },
	{ "meaning": "groan", "group": "Emotions and values" },
	{ "meaning": "easy", "group": "Cognition" },
	{ "meaning": "gun, cannon", "group": "Warfare and hunting" },
	{ "meaning": "sorcerer, witch", "group": "Religion and belief" },
	{ "meaning": "early", "group": "Time" },
	{ "meaning": "three", "group": "Quantity" },
	{ "meaning": "save, rescue", "group": "Possession" },
	{ "meaning": "wheel", "group": "Motion" },
	{ "meaning": "iron", "group": "Basic actions and technology" },
	{ "meaning": "window", "group": "The house" },
	{ "meaning": "soap", "group": "Clothing and grooming" },
	{ "meaning": "ring (for finger)", "group": "Clothing and grooming" },
	{ "meaning": "shirt", "group": "Clothing and grooming" },
	{ "meaning": "sugar", "group": "Food and drink" },
	{ "meaning": "hiccough", "group": "The body" },
	{ "meaning": "womb", "group": "The body" },
	{ "meaning": "spider web", "group": "Animals" },
	{ "meaning": "feel", "group": "Sense perception" },
	{ "meaning": "wrinkled", "group": "Sense perception" },
	{ "meaning": "deceit", "group": "Emotions and values" },
	{ "meaning": "call (=name)", "group": "Speech and language" },
	{ "meaning": "staff, walking stick", "group": "Social and political relations" },
	{ "meaning": "retard, delay", "group": "Time" },
	{ "meaning": "pair", "group": "Quantity" },
	{ "meaning": "inside, in", "group": "Spatial relations" },
	{ "meaning": "destroy", "group": "Possession" },
	{ "meaning": "boat", "group": "Motion" },
	{ "meaning": "pillow", "group": "The house" },
	{ "meaning": "pitcher, jug", "group": "Food and drink" },
	{ "meaning": "break wind", "group": "The body" },
	{ "meaning": "gums", "group": "The body" },
	{ "meaning": "twins", "group": "Kinship" },
	{ "meaning": "valley", "group": "The physical world" },
	{ "meaning": "taste", "group": "Sense perception" },
	{ "meaning": "loud", "group": "Sense perception" },
	{ "meaning": "ghost, phantom", "group": "Religion and belief" },
	{ "meaning": "end (temporal)", "group": "Time" },
	{ "meaning": "hook", "group": "Spatial relations" },
	{ "meaning": "borrow", "group": "Possession" },
	{ "meaning": "lend", "group": "Possession" },
	{ "meaning": "carry-on-shoulder", "group": "Motion" },
	{ "meaning": "drop (vb)", "group": "Motion" },
	{ "meaning": "paint (vb)", "group": "Basic actions and technology" },
	{ "meaning": "broken", "group": "Basic actions and technology" },
	{ "meaning": "garden", "group": "Agriculture and vegetation" },
	{ "meaning": "scar", "group": "The body" },
	{ "meaning": "calf", "group": "Animals" },
	{ "meaning": "bull", "group": "Animals" },
	{ "meaning": "cousin", "group": "Kinship" },
	{ "meaning": "day-after-tomorrow", "group": "Time" },
	{ "meaning": "pity", "group": "Emotions and values" },
	{ "meaning": "flute", "group": "Speech and language" },
	{ "meaning": "master", "group": "Social and political relations" },
	{ "meaning": "south", "group": "Spatial relations" },
	{ "meaning": "silver", "group": "Basic actions and technology" },
	{ "meaning": "saw", "group": "Basic actions and technology" },
	{ "meaning": "gourd", "group": "Agriculture and vegetation" },
	{ "meaning": "rice", "group": "Agriculture and vegetation" },
	{ "meaning": "dark (in color)", "group": "Sense perception" },
	{ "meaning": "wrong", "group": "Emotions and values" },
	{ "meaning": "because", "group": "Cognition" },
	{ "meaning": "drum", "group": "Speech and language" },
	{ "meaning": "command, order", "group": "Social and political relations" },
	{ "meaning": "twenty", "group": "Quantity" },
	{ "meaning": "trade, barter", "group": "Possession" },
	{ "meaning": "give back", "group": "Possession" },
	{ "meaning": "drive", "group": "Motion" },
	{ "meaning": "hammer", "group": "Basic actions and technology" },
	{ "meaning": "ice", "group": "The physical world" },
	{ "meaning": "think (= be of the opinion)", "group": "Cognition" },
	{ "meaning": "clear, plain", "group": "Cognition" },
	{ "meaning": "God", "group": "Religion and belief" },
	{ "meaning": "two times", "group": "Quantity" },
	{ "meaning": "circle", "group": "Spatial relations" },
	{ "meaning": "north", "group": "Spatial relations" },
	{ "meaning": "pick up", "group": "Spatial relations" },
	{ "meaning": "up, above", "group": "Spatial relations" },
	{ "meaning": "down, below", "group": "Spatial relations" },
	{ "meaning": "behind", "group": "Spatial relations" },
	{ "meaning": "ride", "group": "Motion" },
	{ "meaning": "hollow out", "group": "Basic actions and technology" },
	{ "meaning": "sugar cane", "group": "Agriculture and vegetation" },
	{ "meaning": "sheep", "group": "Animals" },
	{ "meaning": "widower", "group": "Kinship" },
	{ "meaning": "stepmother", "group": "Kinship" },
	{ "meaning": "father's brother", "group": "Kinship" },
	{ "meaning": "mother's brother", "group": "Kinship" },
	{ "meaning": "long-time (for a)", "group": "Time" },
	{ "meaning": "and", "group": "Cognition" },
	{ "meaning": "whisper", "group": "Speech and language" },
	{ "meaning": "soldier", "group": "Warfare and hunting" },
	{ "meaning": "trap (noun)", "group": "Warfare and hunting" },
	{ "meaning": "weigh", "group": "Possession" },
	{ "meaning": "price", "group": "Possession" },
	{ "meaning": "dive", "group": "Motion" },
	{ "meaning": "pumpkin, squash", "group": "Agriculture and vegetation" },
	{ "meaning": "yard, court", "group": "The house" },
	{ "meaning": "grasshopper", "group": "Animals" },
	{ "meaning": "shell", "group": "Animals" },
	{ "meaning": "goat", "group": "Animals" },
	{ "meaning": "spear", "group": "Warfare and hunting" },
	{ "meaning": "room", "group": "The house" },
	{ "meaning": "mortar (2)", "group": "Food and drink" },
	{ "meaning": "dish", "group": "Food and drink" },
	{ "meaning": "bake", "group": "Food and drink" },
	{ "meaning": "blister", "group": "The body" },
	{ "meaning": "neighbor", "group": "Social and political relations" },
	{ "meaning": "outside", "group": "Spatial relations" },
	{ "meaning": "fox", "group": "Animals" },
	{ "meaning": "boar", "group": "Animals" },
	{ "meaning": "aunt", "group": "Kinship" },
	{ "meaning": "parents", "group": "Kinship" },
	{ "meaning": "day-before-yesterday", "group": "Time" },
	{ "meaning": "smile", "group": "Emotions and values" },
	{ "meaning": "praise", "group": "Emotions and values" },
	{ "meaning": "rebuke, scold", "group": "Speech and language" },
	{ "meaning": "servant", "group": "Social and political relations" },
	{ "meaning": "club", "group": "Warfare and hunting" },
	{ "meaning": "carriage, wagon, cart", "group": "Motion" },
	{ "meaning": "crouch", "group": "Motion" },
	{ "meaning": "paint (noun)", "group": "Basic actions and technology" },
	{ "meaning": "mat", "group": "Basic actions and technology" },
	{ "meaning": "sap", "group": "Agriculture and vegetation" },
	{ "meaning": "grain (barley, oats etc)", "group": "Agriculture and vegetation" },
	{ "meaning": "candle", "group": "The house" },
	{ "meaning": "bracelet", "group": "Clothing and grooming" },
	{ "meaning": "meal (a)", "group": "Food and drink" },
	{ "meaning": "father's sister", "group": "Kinship" },
	{ "meaning": "uncle", "group": "Kinship" },
	{ "meaning": "surprised, astonished", "group": "Emotions and values" },
	{ "meaning": "mistake, error", "group": "Emotions and values" },
	{ "meaning": "wise", "group": "Cognition" },
	{ "meaning": "pupil", "group": "Cognition" },
	{ "meaning": "if", "group": "Cognition" },
	{ "meaning": "hinder, prevent", "group": "Social and political relations" },
	{ "meaning": "fishnet", "group": "Warfare and hunting" },
	{ "meaning": "murder", "group": "Law" },
	{ "meaning": "curse", "group": "Religion and belief" },
	{ "meaning": "last, endure", "group": "Time" },
	{ "meaning": "three times", "group": "Quantity" },
	{ "meaning": "sphere, ball", "group": "Spatial relations" },
	{ "meaning": "fan (noun)", "group": "Basic actions and technology" },
	{ "meaning": "pound with fist", "group": "Basic actions and technology" },
	{ "meaning": "nit (louse egg)", "group": "Animals" },
	{ "meaning": "cattle (bovine)", "group": "Animals" },
	{ "meaning": "stepfather", "group": "Kinship" },
	{ "meaning": "let, permit", "group": "Social and political relations" },
	{ "meaning": "war, battle", "group": "Warfare and hunting" },
	{ "meaning": "prison, jail", "group": "Law" },
	{ "meaning": "before", "group": "Spatial relations" },
	{ "meaning": "scorpion", "group": "Animals" },
	{ "meaning": "son-in-law (of a woman)", "group": "Kinship" },
	{ "meaning": "mother-in-law (of a woman)", "group": "Kinship" },
	{ "meaning": "father-in-law (of a woman)", "group": "Kinship" },
	{ "meaning": "mother's sister", "group": "Kinship" },
	{ "meaning": "offspring (son or daughter)", "group": "Kinship" },
	{ "meaning": "imitate", "group": "Cognition" },
	{ "meaning": "need, necessity", "group": "Cognition" },
	{ "meaning": "forbid", "group": "Speech and language" },
	{ "meaning": "custom", "group": "Social and political relations" },
	{ "meaning": "hundred", "group": "Quantity" },
	{ "meaning": "eleven", "group": "Quantity" },
	{ "meaning": "under", "group": "Spatial relations" },
	{ "meaning": "own, possess", "group": "Possession" },
	{ "meaning": "skirt", "group": "Clothing and grooming" },
	{ "meaning": "knead", "group": "Food and drink" },
	{ "meaning": "cockroach", "group": "Animals" },
	{ "meaning": "island", "group": "The physical world" },
	{ "meaning": "never", "group": "Time" },
	{ "meaning": "blame", "group": "Emotions and values" },
	{ "meaning": "guest", "group": "Social and political relations" },
	{ "meaning": "ready", "group": "Time" },
	{ "meaning": "bamboo", "group": "Agriculture and vegetation" },
	{ "meaning": "mow, reap", "group": "Agriculture and vegetation" },
	{ "meaning": "milk (vb)", "group": "Food and drink" },
	{ "meaning": "pestle", "group": "Food and drink" },
	{ "meaning": "shoulderblade", "group": "The body" },
	{ "meaning": "centipede", "group": "Animals" },
	{ "meaning": "air", "group": "The physical world" },
	{ "meaning": "clever", "group": "Emotions and values" },
	{ "meaning": "study", "group": "Cognition" },
	{ "meaning": "school", "group": "Cognition" },
	{ "meaning": "sure, certain", "group": "Cognition" },
	{ "meaning": "explain", "group": "Cognition" },
	{ "meaning": "often", "group": "Time" },
	{ "meaning": "beggar", "group": "Possession" },
	{ "meaning": "splash", "group": "Motion" },
	{ "meaning": "fan (vb)", "group": "Basic actions and technology" },
	{ "meaning": "dye", "group": "Clothing and grooming" },
	{ "meaning": "soon", "group": "Time" },
	{ "meaning": "four", "group": "Quantity" },
	{ "meaning": "debt", "group": "Possession" },
	{ "meaning": "owe", "group": "Possession" },
	{ "meaning": "vine", "group": "Agriculture and vegetation" },
	{ "meaning": "shovel", "group": "Agriculture and vegetation" },
	{ "meaning": "button", "group": "Clothing and grooming" },
	{ "meaning": "bread", "group": "Food and drink" },
	{ "meaning": "molartooth", "group": "The body" },
	{ "meaning": "fin (dorsal)", "group": "Animals" },
	{ "meaning": "sow (2)", "group": "Animals" },
	{ "meaning": "earthquake", "group": "The physical world" },
	{ "meaning": "sometimes", "group": "Time" },
	{ "meaning": "after", "group": "Spatial relations" },
	{ "meaning": "limp", "group": "Motion" },
	{ "meaning": "glass", "group": "Basic actions and technology" },
	{ "meaning": "beam", "group": "The house" },
	{ "meaning": "handkerchief, rag", "group": "Clothing and grooming" },
	{ "meaning": "divorce", "group": "Kinship" },
	{ "meaning": "regret, be sorry", "group": "Emotions and values" },
	{ "meaning": "secret", "group": "Cognition" },
	{ "meaning": "promise", "group": "Speech and language" },
	{ "meaning": "pen", "group": "Speech and language" },
	{ "meaning": "miss (target)", "group": "Warfare and hunting" },
	{ "meaning": "heaven", "group": "Religion and belief" },
	{ "meaning": "thousand", "group": "Quantity" },
	{ "meaning": "wages", "group": "Possession" },
	{ "meaning": "tree stump", "group": "Agriculture and vegetation" },
	{ "meaning": "key", "group": "The house" },
	{ "meaning": "pan", "group": "Food and drink" },
	{ "meaning": "daughter-in-law (of a woman)", "group": "Kinship" },
	{ "meaning": "noon, midday", "group": "Time" },
	{ "meaning": "light (in color)", "group": "Sense perception" },
	{ "meaning": "fault", "group": "Emotions and values" },
	{ "meaning": "mind", "group": "Cognition" },
	{ "meaning": "announce", "group": "Speech and language" },
	{ "meaning": "magic, witchcraft, sorcery", "group": "Religion and belief" },
	{ "meaning": "age", "group": "Time" },
	{ "meaning": "twelve", "group": "Quantity" },
	{ "meaning": "coin", "group": "Possession" },
	{ "meaning": "carry-in-hand", "group": "Motion" },
	{ "meaning": "famine", "group": "Food and drink" },
	{ "meaning": "beehive", "group": "Animals" },
	{ "meaning": "mare", "group": "Animals" },
	{ "meaning": "sniff", "group": "Sense perception" },
	{ "meaning": "proud", "group": "Emotions and values" },
	{ "meaning": "admit, confess", "group": "Speech and language" },
	{ "meaning": "five", "group": "Quantity" },
	{ "meaning": "line", "group": "Spatial relations" },
	{ "meaning": "far (adv)", "group": "Spatial relations" },
	{ "meaning": "bunch", "group": "Food and drink" },
	{ "meaning": "beeswax", "group": "Animals" },
	{ "meaning": "ox", "group": "Animals" },
	{ "meaning": "pasture", "group": "Animals" },
	{ "meaning": "hope", "group": "Emotions and values" },
	{ "meaning": "seem", "group": "Cognition" },
	{ "meaning": "victory", "group": "Warfare and hunting" },
	{ "meaning": "defend", "group": "Warfare and hunting" },
	{ "meaning": "fisherman", "group": "Warfare and hunting" },
	{ "meaning": "pray", "group": "Religion and belief" },
	{ "meaning": "fifteen", "group": "Quantity" },
	{ "meaning": "canoe", "group": "Motion" },
	{ "meaning": "glue", "group": "Basic actions and technology" },
	{ "meaning": "sweet potato", "group": "Agriculture and vegetation" },
	{ "meaning": "thresh", "group": "Agriculture and vegetation" },
	{ "meaning": "trough", "group": "The house" },
	{ "meaning": "woman's dress", "group": "Clothing and grooming" },
	{ "meaning": "fur", "group": "Clothing and grooming" },
	{ "meaning": "kettle", "group": "Food and drink" },
	{ "meaning": "freshwater eel", "group": "Animals" },
	{ "meaning": "whirlpool", "group": "The physical world" },
	{ "meaning": "wave", "group": "The physical world" },
	{ "meaning": "danger", "group": "Emotions and values" },
	{ "meaning": "greedy", "group": "Emotions and values" },
	{ "meaning": "doubt", "group": "Cognition" },
	{ "meaning": "threaten", "group": "Speech and language" },
	{ "meaning": "boundary", "group": "Social and political relations" },
	{ "meaning": "front", "group": "Spatial relations" },
	{ "meaning": "market (place)", "group": "Possession" },
	{ "meaning": "release, let go", "group": "Possession" },
	{ "meaning": "chain", "group": "Basic actions and technology" },
	{ "meaning": "crow", "group": "Animals" },
	{ "meaning": "descendants", "group": "Kinship" },
	{ "meaning": "waterfall", "group": "The physical world" },
	{ "meaning": "clock, timepiece", "group": "Time" },
	{ "meaning": "forgive", "group": "Emotions and values" },
	{ "meaning": "howl", "group": "Speech and language" },
	{ "meaning": "sword", "group": "Warfare and hunting" },
	{ "meaning": "crop, harvest", "group": "Agriculture and vegetation" },
	{ "meaning": "hoe", "group": "Agriculture and vegetation" },
	{ "meaning": "pocket", "group": "Clothing and grooming" },
	{ "meaning": "beget (of father)", "group": "The body" },
	{ "meaning": "pubic hair", "group": "The body" },
	{ "meaning": "firefly", "group": "Animals" },
	{ "meaning": "lion", "group": "Animals" },
	{ "meaning": "wolf", "group": "Animals" },
	{ "meaning": "penalty, punishment", "group": "Law" },
	{ "meaning": "second", "group": "Quantity" },
	{ "meaning": "store, shop", "group": "Possession" },
	{ "meaning": "plow", "group": "Agriculture and vegetation" },
	{ "meaning": "bruise", "group": "The body" },
	{ "meaning": "crocodile, alligator", "group": "Animals" },
	{ "meaning": "foal, colt", "group": "Animals" },
	{ "meaning": "herdsman", "group": "Animals" },
	{ "meaning": "stepson", "group": "Kinship" },
	{ "meaning": "cause", "group": "Cognition" },
	{ "meaning": "shriek, screech", "group": "Speech and language" },
	{ "meaning": "retreat", "group": "Warfare and hunting" },
	{ "meaning": "temple, church", "group": "Religion and belief" },
	{ "meaning": "cross", "group": "Spatial relations" },
	{ "meaning": "merchant", "group": "Possession" },
	{ "meaning": "razor", "group": "Clothing and grooming" },
	{ "meaning": "mill", "group": "Food and drink" },
	{ "meaning": "stallion", "group": "Animals" },
	{ "meaning": "hour", "group": "Time" },
	{ "meaning": "horn, trumpet", "group": "Speech and language" },
	{ "meaning": "time", "group": "Time" },
	{ "meaning": "beside", "group": "Spatial relations" },
	{ "meaning": "forked branch", "group": "Agriculture and vegetation" },
	{ "meaning": "egg yolk", "group": "Food and drink" },
	{ "meaning": "sandfly (midge), gnat", "group": "Animals" },
	{ "meaning": "stable, stall", "group": "Animals" },
	{ "meaning": "good fortune, luck", "group": "Emotions and values" },
	{ "meaning": "defeat", "group": "Warfare and hunting" },
	{ "meaning": "third", "group": "Quantity" },
	{ "meaning": "banana tree", "group": "Agriculture and vegetation" },
	{ "meaning": "thatch", "group": "The house" },
	{ "meaning": "spindle", "group": "Clothing and grooming" },
	{ "meaning": "fermented drink", "group": "Food and drink" },
	{ "meaning": "oven", "group": "Food and drink" },
	{ "meaning": "dribble", "group": "The body" },
	{ "meaning": "vulture", "group": "Animals" },
	{ "meaning": "heron", "group": "Animals" },
	{ "meaning": "color", "group": "Sense perception" },
	{ "meaning": "king, ruler", "group": "Social and political relations" },
	{ "meaning": "oar", "group": "Motion" },
	{ "meaning": "bead", "group": "Clothing and grooming" },
	{ "meaning": "conceive", "group": "The body" },
	{ "meaning": "bear", "group": "Animals" },
	{ "meaning": "rule, govern", "group": "Social and political relations" },
	{ "meaning": "peace", "group": "Warfare and hunting" },
	{ "meaning": "headband, headdress", "group": "Clothing and grooming" },
	{ "meaning": "beverage, drink", "group": "Food and drink" },
	{ "meaning": "side of head, temple", "group": "The body" },
	{ "meaning": "dandruff", "group": "The body" },
	{ "meaning": "guess", "group": "Cognition" },
	{ "meaning": "boast", "group": "Speech and language" },
	{ "meaning": "accuse", "group": "Law" },
	{ "meaning": "fast (vb)", "group": "Religion and belief" },
	{ "meaning": "plant (noun)", "group": "Agriculture and vegetation" },
	{ "meaning": "sickle, scythe", "group": "Agriculture and vegetation" },
	{ "meaning": "earwax", "group": "The body" },
	{ "meaning": "gill", "group": "Animals" },
	{ "meaning": "ass, donkey", "group": "Animals" },
	{ "meaning": "stutter, stammer", "group": "Speech and language" },
	{ "meaning": "deny", "group": "Speech and language" },
	{ "meaning": "tribe, clan", "group": "Social and political relations" },
	{ "meaning": "zero, nothing", "group": "Quantity" },
	{ "meaning": "copper, bronze", "group": "Basic actions and technology" },
	{ "meaning": "spade", "group": "Agriculture and vegetation" },
	{ "meaning": "collar", "group": "Clothing and grooming" },
	{ "meaning": "snow (noun)", "group": "The physical world" },
	{ "meaning": "worship", "group": "Religion and belief" },
	{ "meaning": "priest", "group": "Religion and belief" },
	{ "meaning": "tool", "group": "Basic actions and technology" },
	{ "meaning": "ridgepole", "group": "The house" },
	{ "meaning": "lock (noun)", "group": "The house" },
	{ "meaning": "towel", "group": "Clothing and grooming" },
	{ "meaning": "wool", "group": "Clothing and grooming" },
	{ "meaning": "pepper", "group": "Food and drink" },
	{ "meaning": "eagle", "group": "Animals" },
	{ "meaning": "goose", "group": "Animals" },
	{ "meaning": "ram", "group": "Animals" },
	{ "meaning": "marriage, wedding", "group": "Kinship" },
	{ "meaning": "one's native country", "group": "Social and political relations" },
	{ "meaning": "weapons, arms", "group": "Warfare and hunting" },
	{ "meaning": "six", "group": "Quantity" },
	{ "meaning": "rafter", "group": "The house" },
	{ "meaning": "stocking, sock", "group": "Clothing and grooming" },
	{ "meaning": "breakfast", "group": "Food and drink" },
	{ "meaning": "stepdaughter", "group": "Kinship" },
	{ "meaning": "week", "group": "Time" },
	{ "meaning": "dare", "group": "Emotions and values" },
	{ "meaning": "host", "group": "Social and political relations" },
	{ "meaning": "army", "group": "Warfare and hunting" },
	{ "meaning": "carry-on-head", "group": "Motion" },
	{ "meaning": "carpenter", "group": "Basic actions and technology" },
	{ "meaning": "Sunday", "group": "Time" },
	{ "meaning": "season", "group": "Time" },
	{ "meaning": "misfortune, bad luck", "group": "Emotions and values" },
	{ "meaning": "slave", "group": "Social and political relations" },
	{ "meaning": "sling", "group": "Warfare and hunting" },
	{ "meaning": "eight", "group": "Quantity" },
	{ "meaning": "row (vb)", "group": "Motion" },
	{ "meaning": "ship", "group": "Motion" },
	{ "meaning": "fireplace", "group": "The house" },
	{ "meaning": "sibling", "group": "Kinship" },
	{ "meaning": "or", "group": "Cognition" },
	{ "meaning": "nine", "group": "Quantity" },
	{ "meaning": "awl", "group": "Clothing and grooming" },
	{ "meaning": "udder", "group": "The body" },
	{ "meaning": "ewe", "group": "Animals" },
	{ "meaning": "married woman", "group": "Kinship" },
	{ "meaning": "married man", "group": "Kinship" },
	{ "meaning": "speech (make a)", "group": "Speech and language" },
	{ "meaning": "attack", "group": "Warfare and hunting" },
	{ "meaning": "fishing line", "group": "Warfare and hunting" },
	{ "meaning": "seven", "group": "Quantity" },
	{ "meaning": "carve", "group": "Basic actions and technology" },
	{ "meaning": "pipe", "group": "Agriculture and vegetation" },
	{ "meaning": "vegetables", "group": "Food and drink" },
	{ "meaning": "tongs", "group": "Food and drink" },
	{ "meaning": "insect", "group": "Animals" },
	{ "meaning": "kid", "group": "Animals" },
	{ "meaning": "captive, prisoner", "group": "Warfare and hunting" },
	{ "meaning": "law", "group": "Law" },
	{ "meaning": "farmer", "group": "Agriculture and vegetation" },
	{ "meaning": "brick", "group": "The house" },
	{ "meaning": "potato", "group": "Food and drink" },
	{ "meaning": "lunch", "group": "Food and drink" },
	{ "meaning": "he-goat", "group": "Animals" },
	{ "meaning": "livestock", "group": "Animals" },
	{ "meaning": "ocean", "group": "The physical world" },
	{ "meaning": "guard, sentinel", "group": "Warfare and hunting" },
	{ "meaning": "square", "group": "Spatial relations" },
	{ "meaning": "earn", "group": "Possession" },
	{ "meaning": "tapioca, manioc, cassava", "group": "Agriculture and vegetation" },
	{ "meaning": "palm tree", "group": "Agriculture and vegetation" },
	{ "meaning": "hay", "group": "Agriculture and vegetation" },
	{ "meaning": "rake", "group": "Agriculture and vegetation" },
	{ "meaning": "stove", "group": "The house" },
	{ "meaning": "ornament, adornment", "group": "Clothing and grooming" },
	{ "meaning": "coat", "group": "Clothing and grooming" },
	{ "meaning": "carry-underarm", "group": "Motion" },
	{ "meaning": "ointment", "group": "Clothing and grooming" },
	{ "meaning": "chili pepper", "group": "Food and drink" },
	{ "meaning": "dough", "group": "Food and drink" },
	{ "meaning": "sacrifice, offering", "group": "Religion and belief" },
	{ "meaning": "lamb", "group": "Animals" },
	{ "meaning": "intention, purpose", "group": "Cognition" },
	{ "meaning": "prostitute", "group": "Social and political relations" },
	{ "meaning": "bait", "group": "Warfare and hunting" },
	{ "meaning": "nut", "group": "Food and drink" },
	{ "meaning": "Monday", "group": "Time" },
	{ "meaning": "Saturday", "group": "Time" },
	{ "meaning": "land (vb)", "group": "Motion" },
	{ "meaning": "collarbone", "group": "The body" },
	{ "meaning": "idea, notion", "group": "Cognition" },
	{ "meaning": "suspect", "group": "Cognition" },
	{ "meaning": "way, manner", "group": "Cognition" },
	{ "meaning": "refuse", "group": "Speech and language" },
	{ "meaning": "hire", "group": "Possession" },
	{ "meaning": "smith, blacksmith", "group": "Basic actions and technology" },
	{ "meaning": "nettle", "group": "Agriculture and vegetation" },
	{ "meaning": "shelf", "group": "The house" },
	{ "meaning": "latch, door-bolt", "group": "The house" },
	{ "meaning": "tailor", "group": "Clothing and grooming" },
	{ "meaning": "beer", "group": "Food and drink" },
	{ "meaning": "goiter", "group": "The body" },
	{ "meaning": "spleen", "group": "The body" },
	{ "meaning": "Thursday", "group": "Time" },
	{ "meaning": "Friday", "group": "Time" },
	{ "meaning": "faithful", "group": "Emotions and values" },
	{ "meaning": "obscure", "group": "Cognition" },
	{ "meaning": "innocent", "group": "Law" },
	{ "meaning": "fork (2)", "group": "Food and drink" },
	{ "meaning": "fowl", "group": "Animals" },
	{ "meaning": "we (inclusive)", "group": "Kinship" },
	{ "meaning": "Tuesday", "group": "Time" },
	{ "meaning": "Wednesday", "group": "Time" },
	{ "meaning": "spring", "group": "Time" },
	{ "meaning": "autumn", "group": "Time" },
	{ "meaning": "ambush", "group": "Warfare and hunting" },
	{ "meaning": "adultery", "group": "Law" },
	{ "meaning": "mule", "group": "Animals" },
	{ "meaning": "calm (of sea)", "group": "The physical world" },
	{ "meaning": "trap (vb)", "group": "Warfare and hunting" },
	{ "meaning": "hell", "group": "Religion and belief" },
	{ "meaning": "keep, retain", "group": "Possession" },
	{ "meaning": "lead (noun)", "group": "Basic actions and technology" },
	{ "meaning": "wine", "group": "Food and drink" },
	{ "meaning": "account, reckoning", "group": "Possession" },
	{ "meaning": "chisel", "group": "Basic actions and technology" },
	{ "meaning": "wheat", "group": "Agriculture and vegetation" },
	{ "meaning": "cookhouse", "group": "The house" },
	{ "meaning": "cloak", "group": "Clothing and grooming" },
	{ "meaning": "saucer", "group": "Food and drink" },
	{ "meaning": "earlobe", "group": "The body" },
	{ "meaning": "elephant", "group": "Animals" },
	{ "meaning": "weather", "group": "The physical world" },
	{ "meaning": "surrender", "group": "Warfare and hunting" },
	{ "meaning": "witness", "group": "Law" },
	{ "meaning": "guilty", "group": "Law" },
	{ "meaning": "netbag", "group": "Basic actions and technology" },
	{ "meaning": "we (exclusive)", "group": "Kinship" },
	{ "meaning": "rattle", "group": "Speech and language" },
	{ "meaning": "judge (vb)", "group": "Law" },
	{ "meaning": "furrow", "group": "Agriculture and vegetation" },
	{ "meaning": "pin", "group": "Clothing and grooming" },
	{ "meaning": "betray", "group": "Cognition" },
	{ "meaning": "harbor, port", "group": "Motion" },
	{ "meaning": "preach", "group": "Religion and belief" },
	{ "meaning": "span, fathom", "group": "Spatial relations" },
	{ "meaning": "mold (clay etc)", "group": "Basic actions and technology" },
	{ "meaning": "tent", "group": "The house" },
	{ "meaning": "brush", "group": "Clothing and grooming" },
	{ "meaning": "loom", "group": "Clothing and grooming" },
	{ "meaning": "fish trap", "group": "Warfare and hunting" },
	{ "meaning": "rape", "group": "Law" },
	{ "meaning": "paddle (noun)", "group": "Motion" },
	{ "meaning": "supper", "group": "Food and drink" },
	{ "meaning": "mumble", "group": "Speech and language" },
	{ "meaning": "bless", "group": "Religion and belief" },
	{ "meaning": "omen, portent", "group": "Religion and belief" },
	{ "meaning": "chimney", "group": "The house" },
	{ "meaning": "grape", "group": "Food and drink" },
	{ "meaning": "holy, sacred", "group": "Religion and belief" },
	{ "meaning": "tax, tribute", "group": "Possession" },
	{ "meaning": "citizen, subject", "group": "Social and political relations" },
	{ "meaning": "raft", "group": "Motion" },
	{ "meaning": "yoke", "group": "Motion" },
	{ "meaning": "glove", "group": "Clothing and grooming" },
	{ "meaning": "silk", "group": "Clothing and grooming" },
	{ "meaning": "altar", "group": "Religion and belief" },
	{ "meaning": "doorpost, jamb", "group": "The house" },
	{ "meaning": "tin, tinplate", "group": "Basic actions and technology" },
	{ "meaning": "citrus fruit", "group": "Agriculture and vegetation" },
	{ "meaning": "fork", "group": "Agriculture and vegetation" },
	{ "meaning": "dinner", "group": "Food and drink" },
	{ "meaning": "lagoon", "group": "The physical world" },
	{ "meaning": "fine", "group": "Law" },
	{ "meaning": "shoemaker, cobbler", "group": "Clothing and grooming" },
	{ "meaning": "rough (of sea)", "group": "The physical world" },
	{ "meaning": "queen", "group": "Social and political relations" },
	{ "meaning": "mason", "group": "The house" },
	{ "meaning": "mainland", "group": "The physical world" },
	{ "meaning": "brackish", "group": "Sense perception" },
	{ "meaning": "tattoo", "group": "Clothing and grooming" },
	{ "meaning": "judge (noun)", "group": "Law" },
	{ "meaning": "arson", "group": "Law" },
	{ "meaning": "statue", "group": "Basic actions and technology" },
	{ "meaning": "pine", "group": "Agriculture and vegetation" },
	{ "meaning": "swear", "group": "Law" },
	{ "meaning": "coconut", "group": "Agriculture and vegetation" },
	{ "meaning": "helmet", "group": "Warfare and hunting" },
	{ "meaning": "condemn", "group": "Law" },
	{ "meaning": "religion", "group": "Religion and belief" },
	{ "meaning": "forge", "group": "Basic actions and technology" },
	{ "meaning": "fairy, elf", "group": "Religion and belief" },
	{ "meaning": "potter", "group": "Basic actions and technology" },
	{ "meaning": "threshing-floor", "group": "Agriculture and vegetation" },
	{ "meaning": "shield", "group": "Warfare and hunting" },
	{ "meaning": "judgment", "group": "Law" },
	{ "meaning": "adze", "group": "Basic actions and technology" },
	{ "meaning": "boot", "group": "Clothing and grooming" },
	{ "meaning": "headland, point", "group": "The physical world" },
	{ "meaning": "camel", "group": "Animals" },
	{ "meaning": "gulf, bay", "group": "The physical world" },
	{ "meaning": "cast (metals)", "group": "Basic actions and technology" },
	{ "meaning": "mortar", "group": "The house" },
	{ "meaning": "butter", "group": "Food and drink" },
	{ "meaning": "conspiracy, plot", "group": "Social and political relations" },
	{ "meaning": "booty, spoils", "group": "Warfare and hunting" },
	{ "meaning": "sail (vb)", "group": "Motion" },
	{ "meaning": "court", "group": "Law" },
	{ "meaning": "anchor", "group": "Motion" },
	{ "meaning": "rug", "group": "Basic actions and technology" },
	{ "meaning": "anvil", "group": "Basic actions and technology" },
	{ "meaning": "veil", "group": "Clothing and grooming" },
	{ "meaning": "sausage", "group": "Food and drink" },
	{ "meaning": "idol", "group": "Religion and belief" },
	{ "meaning": "adobe", "group": "The house" },
	{ "meaning": "tower", "group": "Warfare and hunting" },
	{ "meaning": "jewel", "group": "Clothing and grooming" },
	{ "meaning": "acquit", "group": "Law" },
	{ "meaning": "axle", "group": "Motion" },
	{ "meaning": "yam", "group": "Agriculture and vegetation" },
	{ "meaning": "cheese", "group": "Food and drink" },
	{ "meaning": "fig", "group": "Food and drink" },
	{ "meaning": "seagull", "group": "Animals" },
	{ "meaning": "battle-ax", "group": "Warfare and hunting" },
	{ "meaning": "perjury", "group": "Law" },
	{ "meaning": "rudder", "group": "Motion" },
	{ "meaning": "armor (defensive)", "group": "Warfare and hunting" },
	{ "meaning": "oath", "group": "Law" },
	{ "meaning": "convict (vb)", "group": "Law" },
	{ "meaning": "stingray", "group": "Animals" },
	{ "meaning": "fortress", "group": "Warfare and hunting" },
	{ "meaning": "defendant", "group": "Law" },
	{ "meaning": "mead", "group": "Food and drink" },
	{ "meaning": "noble, nobleman", "group": "Social and political relations" },
	{ "meaning": "lowtide", "group": "The physical world" },
	{ "meaning": "sail (noun)", "group": "Motion" },
	{ "meaning": "meeting house", "group": "The house" },
	{ "meaning": "garden-house", "group": "The house" },
	{ "meaning": "linen, flax", "group": "Clothing and grooming" },
	{ "meaning": "mast", "group": "Motion" },
	{ "meaning": "barley", "group": "Agriculture and vegetation" },
	{ "meaning": "oats", "group": "Agriculture and vegetation" },
	{ "meaning": "arch", "group": "The house" },
	{ "meaning": "whale", "group": "Animals" },
	{ "meaning": "plaintiff", "group": "Law" },
	{ "meaning": "hightide", "group": "The physical world" },
	{ "meaning": "olive", "group": "Food and drink" },
	{ "meaning": "porpoise, dolphin", "group": "Animals" },
	{ "meaning": "banyan", "group": "Agriculture and vegetation" },
	{ "meaning": "beech", "group": "Agriculture and vegetation" },
	{ "meaning": "poet", "group": "Speech and language" },
	{ "meaning": "fir", "group": "Agriculture and vegetation" },
	{ "meaning": "opossum", "group": "Animals" },
	{ "meaning": "sculptor", "group": "Basic actions and technology" },
	{ "meaning": "shark", "group": "Animals" },
	{ "meaning": "tide", "group": "The physical world" },
	{ "meaning": "oak", "group": "Agriculture and vegetation" },
	{ "meaning": "felt", "group": "Clothing and grooming" },
	{ "meaning": "freeman", "group": "Social and political relations" },
	{ "meaning": "poncho", "group": "Clothing and grooming" },
	{ "meaning": "reef", "group": "The physical world" },
	{ "meaning": "fish poison (root)", "group": "Agriculture and vegetation" },
	{ "meaning": "rye", "group": "Agriculture and vegetation" },
	{ "meaning": "acorn", "group": "Agriculture and vegetation" },
	{ "meaning": "birch", "group": "Agriculture and vegetation" },
	{ "meaning": "outrigger", "group": "Motion" },
	{ "meaning": "grass-skirt", "group": "Clothing and grooming" },
	{ "meaning": "men's house", "group": "The house" },
	{ "group": "" }
]
